# Generated by Django 4.1.7 on 2023-03-12 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Record",
            new_name="UserDetails",
        ),
    ]
